/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gdufs.view;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import org.gdufs.controller.FrameFactory;
import org.gdufs.dao.IMailDao;
import org.gdufs.dao.impl.MailDao;
import org.gdufs.entity.Account;
import org.gdufs.entity.Mail;
import org.gdufs.entity.MailServiceAddress;
import org.gdufs.pub.AccountHandler;
import org.gdufs.pub.MailServiceFactory;
import org.gdufs.service.IClassifier;
import org.gdufs.service.IMailService;
import org.gdufs.service.impl.Classifier;

/**
 *
 * @author Administrator
 */
public class ReceiveMail extends javax.swing.JFrame {

    /**
     * Creates new form ReceiveMail
     */
    public ReceiveMail() {
        initComponents();
        setLocationRelativeTo(null);
        jProgressBar1.setValue(0);
        jProgressBar1.setMaximum(100);
        //执行新邮件获取,垃圾邮件识别
        new ReceiveMailWorker(this, jProgressBar1, jLabelProcessMessage).execute();
    }
    
    /**
     * 邮件获取线程
     */
    static class ReceiveMailWorker extends SwingWorker<String, Object>{
        
        private JProgressBar jpb = null;
        private JLabel label = null;
        private JFrame frame = null;
        public ReceiveMailWorker(JFrame frame, JProgressBar jpb, JLabel label){
            this.jpb = jpb;
            this.label = label;
            this.frame = frame;
        }
        @Override
        protected String doInBackground() throws Exception {
            //1.获取邮件
            Account user = AccountHandler.getLoginAccount();
            IMailService mailService = MailServiceFactory.getMailService();
            String server = MailServiceAddress.getPopAddress(user.getA_account());
            List<Mail> mailList = mailService.getRecentMail(server, user);            
            jpb.setValue(50);
            //2.垃圾邮件过滤
            label.setText("收取邮件完成，正在识别垃圾邮件..");
            int length = mailList.size();
            IClassifier classfier = new Classifier();
            for(int i=0; i<length ;++i){
            	Mail m = mailList.get(i);
            	classfier.categoryOneMail(m);
            	int value = 50+ (int)((1.0*i/length)*50);
            	jpb.setValue(value);
            }
           
            //3.插入新邮件到数据库中
            label.setText("识别完成，正在保存操作结果..");
            IMailDao mdao = new MailDao();
            mdao.insertBatchMail(mailList);
            jpb.setValue(100);
            label.setText("操作完成！");
            return null;
        }
        
        @Override
        protected void done(){
            //完成邮件获取后,启动主界面，关闭当前界面
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    FrameFactory.getMainFrame().setVisible(true);
                }
            });
            this.frame.setVisible(false);
            this.frame.dispose();//关闭资源
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelProcessMessage = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ftn_drag_over1.png"))); // NOI18N

        jLabelProcessMessage.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabelProcessMessage.setText("正在收取邮件，请稍候...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelProcessMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabelProcessMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiveMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiveMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiveMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiveMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReceiveMail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelProcessMessage;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
