/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gdufs.view;

/**
 *
 * @author Administrator
 */
public class UserInfo extends javax.swing.JFrame {

    /**
     * Creates new form UserInfo
     */
    public UserInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNo = new javax.swing.JButton();
        jButtonYes = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel = new javax.swing.JPanel();
        jRadioButtonAccount = new javax.swing.JRadioButton();
        jButtonImport = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jPanelDisplayInfo = new javax.swing.JPanel();
        jLabelEMail = new javax.swing.JLabel();
        jLabelPwd = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldPwd = new javax.swing.JPasswordField();
        jCheckBoxAutoReceive = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldReceiveSequence = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("”√ªß–≈œ¢");

        jButtonNo.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        jButtonNo.setText("»°œ˚");

        jButtonYes.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        jButtonYes.setText("»∑∂®");

        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel.setName("");

        jRadioButtonAccount.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 14)); // NOI18N
        jRadioButtonAccount.setText("545235009@qq.com");

        jButtonImport.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jButtonImport.setText("µº»Î");

        jButtonDelete.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jButtonDelete.setText("…æ≥˝");

        jButtonNew.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jButtonNew.setText("–¬Ω®");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImport)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonNew))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel);

        jPanelDisplayInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelDisplayInfo.setForeground(new java.awt.Color(204, 204, 204));

        jLabelEMail.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jLabelEMail.setText("E-mail:");

        jLabelPwd.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jLabelPwd.setText("√‹¬Î:");

        jTextFieldEmail.setText("’‚¿Ôª·◊‘∂Øœ‘ æ”√ªßµ«¬ºµƒ” œ‰°£°£°£");

        jPasswordFieldPwd.setText("adfladj");
        jPasswordFieldPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPwdActionPerformed(evt);
            }
        });

        jCheckBoxAutoReceive.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jCheckBoxAutoReceive.setText("◊‘∂Ø ’»°” º˛");

        jLabel1.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jLabel1.setText("√ø∏Ù");

        jLabel2.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 12)); // NOI18N
        jLabel2.setText("∑÷÷”");

        javax.swing.GroupLayout jPanelDisplayInfoLayout = new javax.swing.GroupLayout(jPanelDisplayInfo);
        jPanelDisplayInfo.setLayout(jPanelDisplayInfoLayout);
        jPanelDisplayInfoLayout.setHorizontalGroup(
            jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayInfoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPwd)
                    .addComponent(jLabelEMail))
                .addGap(18, 18, 18)
                .addGroup(jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDisplayInfoLayout.createSequentialGroup()
                        .addComponent(jCheckBoxAutoReceive)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldReceiveSequence, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPwd))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelDisplayInfoLayout.setVerticalGroup(
            jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisplayInfoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEMail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPwd)
                    .addComponent(jPasswordFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDisplayInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAutoReceive)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldReceiveSequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelDisplayInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButtonYes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(251, 251, 251)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSplitPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonYes)
                    .addComponent(jButtonNo))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPwdActionPerformed
        // TODO add your handling code jButtonYes}//GEN-LAST:event_jPasswordFieldPwdActionPerformed
    }
        private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JCheckBox jCheckBoxAutoReceive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEMail;
    private javax.swing.JLabel jLabelPwd;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelDisplayInfo;
    private javax.swing.JPasswordField jPasswordFieldPwd;
    private javax.swing.JRadioButton jRadioButtonAccount;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldReceiveSequence;
    // End of variables declaration//GEN-END:variables
}
