/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gdufs.view;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;
import org.gdufs.dao.IMailDao;
import org.gdufs.dao.impl.MailDao;
import org.gdufs.entity.Account;
import org.gdufs.entity.Mail;
import org.gdufs.entity.MailBox;
import org.gdufs.pub.AccountHandler;
import org.gdufs.pub.MailServiceFactory;
import org.gdufs.service.IMailService;

/**
 *
 * @author Administrator
 */
public class WriteMail extends javax.swing.JFrame {

    private Mail mail = null;

    /**
     * Creates new form WriteMail
     */
    public WriteMail() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    public void setMail(Mail m) {
        mail = m;
    }
    
    private void clearAll(){
        this.mail = null;
        jTextFieldReceiver.setText("");
        jTextPaneContent.setText("");
        jTextFieldTopic.setText("");
    }
    
    private void filledMail(int mailBox){
        //填充Mail的内容
        if(mail==null){
            this.mail = new Mail();
        }
        Account a = AccountHandler.getLoginAccount();
        String from = a.getA_account();
        String to = jTextFieldReceiver.getText().trim();
        String content = jTextPaneContent.getText();
        String subject = jTextFieldTopic.getText();
        DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM, Locale.CHINA);
        mail.setA_id(a.getA_id());
        mail.setM_receiver(to);
        mail.setM_sender(from);
        mail.setM_content(content);
        mail.setM_title(subject);
        mail.setB_id(mailBox);
        mail.setM_time(dateFormat.format(new Date()));
    }

    public void setFrame() {
        if (mail == null) {
            return;
        }
        jTextFieldReceiver.setText(mail.getM_receiver());
        jTextFieldTopic.setText(mail.getM_title());
        jTextPaneContent.setText(mail.getM_content());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReceiver = new javax.swing.JLabel();
        jLabelTopic = new javax.swing.JLabel();
        jTextFieldReceiver = new javax.swing.JTextField();
        jTextFieldTopic = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSend = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneContent = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("未命名-写邮件");

        jLabelReceiver.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelReceiver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelReceiver.setText("收件人：");

        jLabelTopic.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabelTopic.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTopic.setText("主题：");

        jButtonSend.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonSend.setText("发送");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jButtonSave.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonSave.setText("存草稿");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClose.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jButtonClose.setText("关闭");

        jScrollPane1.setViewportView(jTextPaneContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReceiver)
                    .addComponent(jLabelTopic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTopic)
                    .addComponent(jTextFieldReceiver)))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap(401, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelReceiver, jLabelTopic});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReceiver)
                    .addComponent(jTextFieldReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTopic)
                    .addComponent(jTextFieldTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // 存草稿 把mail插入数据库           
        this.filledMail(MailBox.DRAFTS); //放到草稿箱
        IMailDao mdao = new MailDao();
        mdao.insertMail(mail);
        //从数据库中取出来，方便下次保存
        this.setTitle("未命名-写邮件  已保存");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // 发送邮件按钮
        //填充内容，保存邮件
        this.filledMail(MailBox.SENTBOX);
        IMailDao mdao = new MailDao();
        mdao.insertMail(mail);
        //发送邮件
        IMailService ms = MailServiceFactory.getMailService();
        ms.sendMail(AccountHandler.getLoginAccount(), mail);
        JOptionPane.showMessageDialog(this, "后台正在进行发送邮件操作");
        clearAll();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WriteMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WriteMail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelReceiver;
    private javax.swing.JLabel jLabelTopic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldReceiver;
    private javax.swing.JTextField jTextFieldTopic;
    private javax.swing.JTextPane jTextPaneContent;
    // End of variables declaration//GEN-END:variables
}
